# Generated by Django 3.1.4 on 2021-01-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('image_url', models.CharField(max_length=512)),
                ('toppings', models.ManyToManyField(blank=True, related_name='belonged_dishes', to='main.Topping')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
